title = "k1"
pluralizelisttitles = false

[params]
favicon = "/img/favicon.ico"

[menu]

  [[menu.main]]
    identifier = "profil"
    name = "Büro"
    url = "/profil"
    weight = 10

  [[menu.main]]
    identifier = "arbeiten"
    name = "Arbeiten"
    url = "/arbeiten"
    weight = 20

  [[menu.sub]]
    identifier = "wettbewerbe"
    name = "Wettbewerbe"
    url = "/wettbewerbe"
    pre = "/"
    weight = 20

  [[menu.sub]]
    identifier = "projekte"
    name = "Projekte"
    url = "/projekte"
    pre = "/"
    weight = 10

  [[menu.sub]]
    identifier = "all"
    name = "Alle"
    url = "/arbeiten"
    weight = 30
    # parent = "arbeiten"


  [[menu.main]]
    identifier = "referenzen"
    name = "Referenzen"
    url = "/referenzen"
    weight = 30

  [[menu.main]]
    identifier = "kontakt"
    name = "Kontakt"
    url = "/kontakt"
    weight = 40

[taxonomies]
  category = "categories"
  tag = "tags"
  type = "type"

[markup]
  defaultMarkdownHandler = 'goldmark'
  [markup.asciidocExt]
    backend = 'html5'
    extensions = []
    failureLevel = 'fatal'
    noHeaderOrFooter = true
    preserveTOC = false
    safeMode = 'unsafe'
    sectionNumbers = false
    trace = false
    verbose = false
    workingFolderCurrent = false
    [markup.asciidocExt.attributes]
  [markup.goldmark]
    [markup.goldmark.extensions]
      definitionList = true
      footnote = true
      linkify = true
      linkifyProtocol = 'https'
      strikethrough = true
      table = true
      taskList = true
      typographer = true
    [markup.goldmark.parser]
      autoHeadingID = true
      autoHeadingIDType = 'github'
      [markup.goldmark.parser.attribute]
        block = false
        title = true
    [markup.goldmark.renderer]
      hardWraps = false
      unsafe = false
      xhtml = false
  [markup.highlight]
    anchorLineNos = false
    codeFences = true
    guessSyntax = false
    hl_Lines = ''
    lineAnchors = ''
    lineNoStart = 1
    lineNos = false
    lineNumbersInTable = true
    noClasses = true
    noHl = false
    style = 'monokai'
    tabWidth = 4
  [markup.tableOfContents]
    endLevel = 3
    ordered = false
    startLevel = 2
