title = "k1"
pluralizelisttitles = false

[menu]

  [[menu.main]]
    identifier = "profil"
    name = "büro"
    url = "/profil"
    weight = 10

  [[menu.main]]
    identifier = "arbeiten"
    name = "arbeiten"
    url = "/arbeiten"
    weight = 20

  [[menu.sub]]
    identifier = "wettbewerbe"
    name = "wettbewerbe"
    url = "/wettbewerbe"
    pre = "/"
    weight = 20
    # parent = "arbeiten"

  [[menu.sub]]
    identifier = "projekte"
    name = "projekte"
    url = "/projekte"
    pre = "/"
    weight = 10
    # parent = "arbeiten"


  [[menu.sub]]
    identifier = "all"
    name = "all"
    url = "/arbeiten"
    weight = 30
    # parent = "arbeiten"


  [[menu.main]]
    identifier = "referenzen"
    name = "referenzen"
    url = "/referenzen"
    weight = 30

  [[menu.main]]
    identifier = "kontakt"
    name = "kontakt"
    url = "/kontakt"
    weight = 40

[taxonomies]
  category = "categories"
  tag = "tags"
  type = "type"
