title = "k1"

[menu]
  # [[menu.main]]
  #   identifier = "home"
  #   name = "k1"
  #   url = "/"
  #   weight = 20

  [[menu.main]]
    identifier = "profil"
    name = "Profil"
    url = "/profil"
    weight = 20

  [[menu.main]]
    identifier = "projekte"
    name = "Projekte"
    url = "/projekte"
    weight = 20

  [[menu.main]]
    identifier = "wettbewerbe"
    name = "Wettbewerbe"
    url = "/wettbewerbe"
    weight = 20

  [[menu.main]]
    identifier = "referenzen"
    name = "Referenzen"
    url = "/referenzen"
    weight = 20
