title = "k1"
pluralizelisttitles = false

[menu]
  # [[menu.main]]
  #   identifier = "home"
  #   name = "Home"
  #   url = "/"
  #   weight = 20

  [[menu.main]]
    identifier = "profil"
    name = "büro"
    url = "/profil"
    weight = 10

  [[menu.main]]
    identifier = "projekte"
    name = "arbeiten"
    url = "/projekte"
    weight = 20

  # [[menu.main]]
  #   identifier = "wettbewerbe"
  #   name = "Wettbewerbe"
  #   url = "/wettbewerbe"
  #   weight = 20

  # [[menu.main]]
  #   identifier = "referenzen"
  #   name = "Referenzen"
  #   url = "/referenzen"
  #   weight = 30

  [[menu.main]]
    identifier = "kontakt"
    name = "kontakt"
    url = "/kontakt"
    weight = 40
