backend:
  name: git-gateway
  branch: main
media_folder: "static/images" # Folder where user uploaded files should go
public_folder: "images"
collections:
  - name: "profil" # Used in routes, e.g., /admin/collections/post
    label: "profil" # Used in the UI
    folder: "content/profil" # The path to the folder where the documents are stored
    path: "{{slug}}/index"
    media_folder: "" # Save images in the post's own folder instead of the static folder
    public_folder: ""
    create: true # Allow users to create new documents in this collection
    fields: # The fields for each document, usually in front matter
      - { label: "Name", name: "name", widget: "string" }
      - { label: "Publish Date", name: "date", widget: "datetime" }
      - { label: "Image", name: "image", widget: "image" }
      - { label: "Bio", name: "bio", widget: "string" }

  - name: "news" # Used in routes, e.g., /admin/collections/post
    label: "news" # Used in the UI
    folder: "content/news" # The path to the folder where the documents are stored
    path: "{{slug}}/index"
    media_folder: "" # Save images in the post's own folder instead of the static folder
    public_folder: ""
    create: true # Allow users to create new documents in this collection
    fields: # The fields for each document, usually in front matter
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Tags", name: "tags", widget: "list", default: "[\"frontpage\"]"}
      - { label: "Publish Date", name: "date", widget: "hidden" }
      - { label: "Image", name: "image", widget: "image", required: false }
      - { label: "Text", name: "text", widget: "markdown" }

  - name: "arbeiten" # Used in routes, e.g., /admin/collections/post
    label: "arbeiten" # Used in the UI
    folder: "content/arbeiten" # The path to the folder where the documents are stored
    path: "{{slug}}/index"
    media_folder: "" # Save images in the post's own folder instead of the static folder
    public_folder: ""
    create: true # Allow users to create new documents in this collection
    fields: # The fields for each document, usually in front matter
      - { label: "Tags", name: "tags", widget: "list", default: "[\"projekt\", \"wbw\", \"frontpage\"]"}
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Year, Place", name: "yearplace", widget: "string", required: false }
      - { label: "Short Info", name: "info", widget: "string", required: false }
      - { label: "Publish Date", name: "date", widget: "hidden" }      
      - { label: "Featured Image", name: "image", widget: "image" }
      - { label: "Body", name: "body", widget: "markdown" }
      - { label: "Image 2", name: "image2", widget: "image", required: false }
      - { label: "Image 3", name: "image3", widget: "image", required: false }
      - { label: "Image 4", name: "image4", widget: "image", required: false }
      - { label: "Image 5", name: "image5", widget: "image", required: false }
      - { label: "Image 6", name: "image6", widget: "image", required: false }
      - { label: "Image 7", name: "image7", widget: "image", required: false }
      - { label: "Image 8", name: "image8", widget: "image", required: false }
      

  - name: "referenzen" # Used in routes, e.g., /admin/collections/post
    label: "referenzen" # Used in the UI
    folder: "content/referenzen" # The path to the folder where the documents are stored
    path: "{{slug}}/index"
    media_folder: "" # Save images in the post's own folder instead of the static folder
    public_folder: ""
    create: true # Allow users to create new documents in this collection
    fields: # The fields for each document, usually in front matter
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Body", name: "body", widget: "markdown" }

  - name: "pages"
    label: "pages"
    files:
      - file: "content/_index.md"
        label: "home page"
        name: "home"
        fields:
          - { label: "Title", name: "title", widget: "string" }
          - { label: "Blurb", name: "blurb", widget: "text" }
          - {
              label: "Section",
              name: "section",
              widget: "object",
              fields:
                [
                  { label: "Heading", name: "heading", widget: string },
                  { label: "Text", name: "text", widget: "text" },
                ],
            }

      - file: "content/kontakt/index.md"
        label: "kontakt"
        name: "kontakt"
        fields:
          - { label: "Title", name: "title", widget: "string" }
          - { label: "Body", name: "body", widget: "markdown" }

