backend:
  name: git-gateway
  branch: main
media_folder: "static/images" # Folder where user uploaded files should go
public_folder: "images"
collections:
  - name: "profil" # Used in routes, e.g., /admin/collections/post
    label: "Profil" # Used in the UI
    folder: "content/profil" # The path to the folder where the documents are stored
    path: "{{slug}}/index"
    media_folder: "" # Save images in the post's own folder instead of the static folder
    public_folder: ""
    create: true # Allow users to create new documents in this collection
    fields: # The fields for each document, usually in front matter
      - { label: "Name", name: "name", widget: "string" }
      - { label: "Publish Date", name: "date", widget: "datetime" }
      - { label: "Image", name: "image", widget: "image" }
      - { label: "Bio", name: "bio", widget: "string" }

  - name: "projekte" # Used in routes, e.g., /admin/collections/post
    label: "Projekte" # Used in the UI
    folder: "content/projekte" # The path to the folder where the documents are stored
    path: "{{slug}}/index"
    media_folder: "" # Save images in the post's own folder instead of the static folder
    public_folder: ""
    create: true # Allow users to create new documents in this collection
    fields: # The fields for each document, usually in front matter
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Publish Date", name: "date", widget: "datetime" }
      - { label: "Featured Image", name: "image", widget: "image" }
      - { label: "Body", name: "body", widget: "markdown" }

  - name: "news" # Used in routes, e.g., /admin/collections/post
    label: "News" # Used in the UI
    folder: "content/news" # The path to the folder where the documents are stored
    path: "{{slug}}/index"
    media_folder: "" # Save images in the post's own folder instead of the static folder
    public_folder: ""
    create: true # Allow users to create new documents in this collection
    fields: # The fields for each document, usually in front matter
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Publish Date", name: "date", widget: "datetime" }
      - { label: "Featured Image", name: "image", widget: "image" }
      - { label: "Body", name: "body", widget: "markdown" }

  - name: "wettbewerbe" # Used in routes, e.g., /admin/collections/post
    label: "Wettbewerbe" # Used in the UI
    folder: "content/wettbewerbe" # The path to the folder where the documents are stored
    path: "{{slug}}/index"
    media_folder: "" # Save images in the post's own folder instead of the static folder
    public_folder: ""
    create: true # Allow users to create new documents in this collection
    fields: # The fields for each document, usually in front matter
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Publish Date", name: "date", widget: "datetime" }
      - { label: "Featured Image", name: "image", widget: "image" }
      - { label: "Image 2", name: "image2", widget: "image", required: false }
      - { label: "Image 3", name: "image3", widget: "image", required: false }
      - { label: "Image 4", name: "image4", widget: "image", required: false }
      - { label: "Image 5", name: "image5", widget: "image", required: false }
      - { label: "Image 6", name: "image6", widget: "image", required: false }
      - { label: "Image 7", name: "image7", widget: "image", required: false }
      - { label: "Image 8", name: "image8", widget: "image", required: false }
      - { label: "Body", name: "body", widget: "markdown" }

  - name: "pages"
    label: "Pages"
    files:
      - file: "content/_index.md"
        label: "Home Page"
        name: "home"
        fields:
          - { label: "Title", name: "title", widget: "string" }
          - { label: "Blurb", name: "blurb", widget: "text" }
          - {
              label: "Section",
              name: "section",
              widget: "object",
              fields:
                [
                  { label: "Heading", name: "heading", widget: string },
                  { label: "Text", name: "text", widget: "text" },
                ],
            }
      - file: "content/referenzen/index.md"
        label: "Referenzen"
        name: "referenzen"
        # path: "{{slug}}/index" layout is always taken from _default - how to change it? 
        fields:
          - { label: "Title", name: "title", widget: "string" }
          - { label: "Body", name: "body", widget: "markdown" }

      - file: "content/kontakt/index.md"
        label: "Kontakt"
        name: "kontakt"
        # path: "{{slug}}/index" layout is always taken from _default - how to change it? 
        fields:
          - { label: "Title", name: "title", widget: "string" }
          - { label: "Body", name: "body", widget: "markdown" }

